name: Deploy React App to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t coinbase-app .

      - name: Tag Docker image
        run: |
          docker tag coinbase-app:latest 851725512876.dkr.ecr.us-west-1.amazonaws.com/coinbase-app:latest
          docker tag coinbase-app:latest 851725512876.dkr.ecr.us-west-1.amazonaws.com/coinbase-app:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push 851725512876.dkr.ecr.us-west-1.amazonaws.com/coinbase-app:latest
          docker push 851725512876.dkr.ecr.us-west-1.amazonaws.com/coinbase-app:${{ github.sha }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: my-react-service
          cluster: react-app-cluster
          wait-for-service-stability: true