name: Deploy React App to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build Docker Image and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 851725512876.dkr.ecr.us-west-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t coinbase-app .

      - name: Tag Docker image for ECR
        run: docker tag coinbase-app:latest 851725512876.dkr.ecr.us-west-1.amazonaws.com/coinbase-app:latest

      - name: Push Docker image to ECR
        run: docker push 851725512876.dkr.ecr.us-west-1.amazonaws.com/coinbase-app:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: react-app-service
          cluster: react-app-cluster
          wait-for-service-stability: true
